/// Codegen para gerar visitors Rust a partir da DSL TOML.
///
/// Este script lê o arquivo rules.toml e gera código Rust para os visitors.

use std::collections::HashMap;
use std::fs;
use std::path::Path;

#[derive(Debug, serde::Deserialize)]
struct RuleConfig {
    query: String,
    message: String,
    severity: String,
    languages: Vec<String>,
}

#[derive(Debug, serde::Deserialize)]
struct RulesToml {
    rule: HashMap<String, RuleConfig>,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-changed=rules.toml");
    
    let rules_path = Path::new("rules.toml");
    let content = fs::read_to_string(rules_path)?;
    let rules: RulesToml = toml::from_str(&content)?;
    
    let mut generated_code = String::new();
    
    // Header do arquivo gerado
    generated_code.push_str("// Auto-generated by build.rs from rules.toml\n");
    generated_code.push_str("// DO NOT EDIT MANUALLY\n\n");
    generated_code.push_str("use crate::lint_rule::{LintRule, Context, Severity, Violation, RuleCategory};\n");
    generated_code.push_str("use crate::parser::ParsedTree;\n\n");
    
    // Gerar um visitor para cada regra
    for (rule_name, rule_config) in &rules.rule {
        let struct_name = format!("{}Visitor", to_pascal_case(rule_name));
        let query = &rule_config.query;
        let message = &rule_config.message;
        let severity = match rule_config.severity.as_str() {
            "error" => "Severity::Error",
            "warning" => "Severity::Warning",
            _ => "Severity::Error",
        };
        
        // Mapear nomes de linguagem para variantes de Language
        let languages: Vec<String> = rule_config.languages.iter()
            .map(|lang| match lang.as_str() {
                "typescript" => "TypeScript",
                "tsx" => "TypeScriptReact",
                "javascript" => "JavaScript",
                "jsx" => "JavaScriptReact",
                _ => lang,
            })
            .map(|lang| format!("crate::language::Language::{}", lang))
            .collect();
        
        generated_code.push_str(&format!(r#"
#[derive(Debug)]
pub struct {struct_name} {{
    query: String,
    message: String,
}}

impl {struct_name} {{
    pub fn new() -> Self {{
        Self {{
            query: "{query}".to_string(),
            message: "{message}".to_string(),
        }}
    }}
}}

impl LintRule for {struct_name} {{
    fn name(&self) -> &str {{
        "{rule_name}"
    }}

    fn category(&self) -> RuleCategory {{
        RuleCategory::Correctness
    }}
    
    fn default_severity(&self) -> Severity {{
        {severity}
    }}
    
    fn supported_languages(&self) -> &[crate::language::Language] {{
        &[
{}
        ]
    }}
    
    fn should_run(&self, _language: crate::language::Language) -> bool {{
        true
    }}
    
    fn visit(&self, _tree: &ParsedTree, _ctx: &Context) -> Vec<Violation> {{
        let violations = Vec::new();
        
        // TODO: Implementar tree-sitter query ou navegação manual
        // Por enquanto, esta é uma implementação placeholder
        
        violations
    }}
}}

"#, languages.join(",\n        ")));
    }
    
    // Função para registrar todos os visitors gerados
    generated_code.push_str("\npub fn register_generated_rules(registry: &mut crate::rule_registry::RuleRegistry) {\n");
    for rule_name in rules.rule.keys() {
        let struct_name = format!("{}Visitor", to_pascal_case(rule_name));
        generated_code.push_str(&format!("    registry.register(Box::new({}::new()));\n", struct_name));
    }
    generated_code.push_str("}\n");
    
    // Escrever o código gerado em OUT_DIR
    let out_dir = std::env::var("OUT_DIR")?;
    let output_path = Path::new(&out_dir).join("generated_visitors.rs");
    fs::write(output_path, generated_code)?;
    
    println!("Generated visitors: {}", rules.rule.len());
    
    Ok(())
}

fn to_pascal_case(s: &str) -> String {
    s.split('-')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

fn to_camel_case(s: &str) -> String {
    s.split('-')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}
